name: NPCTags
version: 1.0
api-version: 1.16
main: me.manaki.plugin.npctags.NPCTags
depend:
  - Citizens
commands:
  npctags:
    description: Nothing
    aliases: [npctag, npct]
    permission: npctags.admin